#.
#Packmakers' control panel for internal recipe compat
[recipes]
	#.
	#.
	#If Bulk Coloring should be enabled
	enableBulkColoring = false
	#.
	#If Bulk Freezing should be enabled
	enableBulkFreezing = true
